FROM pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime

RUN conda install -y -c conda-forge scikit-learn=0.23.2 pytorch-lightning=1.1.4 albumentations=0.5.2 pandas=1.2.0 numpy=1.19.5 timm=0.3.4 && conda clean -ya
